spring:
  application.name: api-app
  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

## 설정 값 분리 필요.
app:
  jwt:
    secret-key: my-secret-key-my-secret-key-my-secret-key
    expiration: 3600

---
spring.config.activate.on-profile: local


---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: live