### 회원가입
POST {{baseUrl}}/v1/signup
Content-Type: application/json

{
  "email": "cyr@test.com",
  "password": "1234",
  "name": "조영래"
}

### 로그인
POST {{baseUrl}}/v1/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "admin"
}


### 채팅 1
POST {{baseUrl}}/v1/chat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "끝말잇기할래?",
  "model": "gpt-4o"
}

### 채팅 2
POST {{baseUrl}}/v1/chat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "과자",
  "model": "gpt-4o"
}

### 채팅 3
POST {{baseUrl}}/v1/chat
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "소방차",
  "model": "gpt-4o"
}

### 대화 목록 조회
GET {{baseUrl}}/v1/threads?page=0&sort=DESC
Authorization: Bearer {{accessToken}}

### 스레드 삭제
DELETE {{baseUrl}}/v1/threads/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 피드백 생성
POST {{baseUrl}}/v1/feedback
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "messageId": 1,
  "type": "POSITIVE"
}


### 피드백 조회
GET {{baseUrl}}/v1/feedbacks
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 피드백 상태 변경
PATCH {{baseUrl}}/v1/feedbacks/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "RESOLVED"
}
