### 회원가입
POST http://localhost:8080/v1/signup
Content-Type: application/json

{
  "email": "cyr@test.com",
  "password": "1234",
  "name": "조영래"
}

### 로그인
POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "email": "cyr@test.com",
  "password": "1234"
}


### 채팅 1
POST http://localhost:8080/v1/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzQzMDk0NzM5LCJleHAiOjE3NDMwOTgzMzl9.5AvT_Y1yE_vUG4fLqn2zPmLSbZKHo2Y7DL7Zk5YC9s8

{
  "content": "끝말잇기할래?",
  "model": "gpt-4o"
}

### 채팅 2
POST http://localhost:8080/v1/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzQzMDk0NzM5LCJleHAiOjE3NDMwOTgzMzl9.5AvT_Y1yE_vUG4fLqn2zPmLSbZKHo2Y7DL7Zk5YC9s8

{
  "content": "이빨",
  "model": "gpt-4o"
}

### 채팅 3
POST http://localhost:8080/v1/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNzQzMDk0NzM5LCJleHAiOjE3NDMwOTgzMzl9.5AvT_Y1yE_vUG4fLqn2zPmLSbZKHo2Y7DL7Zk5YC9s8

{
  "content": "소방차",
  "model": "gpt-4o"
}

### 대화 목록 조회
GET http://localhost:8080/v1/conversations?page=0&sort=DESC
Authorization: Bearer jwt-cyr@test.com

### 스레드 삭제
DELETE http://localhost:8080/v1/threads/1
Content-Type: application/json
Authorization: Bearer jwt-cyr@test.com