create table users
(
    id         bigint       not null generated by default as identity primary key,
    email      varchar(255) not null,
    password   varchar(255) not null,
    name       varchar(45)  not null,
    role       varchar(25)  not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

alter table users
    add constraint uk_users__email unique (email);

create table chat_threads
(
    id         bigint       not null generated by default as identity primary key,
    user_id    bigint       not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);

create index ix_chat_threads__userid_createdat on chat_threads (user_id, created_at desc);
create index ix_chat_threads__createdat on chat_threads (created_at desc);

create table chat_message
(
    id         bigint        not null generated by default as identity primary key,
    thread_id  bigint        not null,
    content    varchar(4000) not null,
    role       varchar(25)   not null,
    chat_at    timestamp(6)  not null,
    created_at timestamp(6)  not null,
    updated_at timestamp(6)  not null
);

create index ix_chat_message__threadid_chatat on chat_message (thread_id, chat_at desc);


create table feedback
(
    id              bigint       not null generated by default as identity primary key,
    user_id         bigint       not null,
    chat_message_id bigint       not null,
    type            varchar(25)  not null,
    status          varchar(25)  not null,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null
);

alter table feedback
    add constraint uk_feedback__chatmessageid_userid unique (chat_message_id, user_id);

create index ix_feedback__createdat on feedback (created_at desc);
create index ix_feedback__userid_createdat on feedback (user_id, created_at desc);

insert into users (email, password, name, role, created_at, updated_at)
values ('admin@test.com', 'admin', 'Admin', 'ADMIN', now(), now());
