create table users
(
    id       bigint       not null generated by default as identity primary key,
    email    varchar(255) not null,
    password varchar(255) not null,
    name     varchar(45)  not null,
    role     varchar(25)  not null
);

alter table users
    add constraint uk_users__email unique (email);