create table example
(
    id         bigint       not null generated by default as identity primary key,
    content    varchar(255) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null
);
